"""initial ecotrace schema

Revision ID: a288b7456c4f
Revises: 
Create Date: 2026-09-13 00:39:00.426469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a288b7456c4f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('facility_name', sa.String(length=255), nullable=False),
    sa.Column('registration_no', sa.String(length=128), nullable=True),
    sa.Column('verification_status', postgresql.ENUM('VERIFIED', 'PENDING', 'EXPIRED', 'UNKNOWN', name='agency_verification_enum'), nullable=False),
    sa.Column('verification_source', sa.String(length=255), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_streams', postgresql.ARRAY(postgresql.ENUM('DRY', 'WET', 'E_WASTE', 'BATTERY', name='waste_stream_enum')), nullable=False),
    sa.Column('capability_tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('agency_id'),
    sa.UniqueConstraint('registration_no')
    )
    op.create_table('knowledge_base_versions',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('release_tag', sa.String(length=64), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'ACTIVE', 'SUPERSEDED', name='kb_release_status_enum'), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('release_tag')
    )
    op.create_table('organizations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('jurisdiction_code', sa.String(length=64), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('address_line', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('organization_id'),
    sa.UniqueConstraint('jurisdiction_code')
    )
    op.create_table('admins',
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('SUPER_ADMIN', 'MUNICIPAL_ADMIN')", name='ck_admin_role'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_events',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('payload_before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload_after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("actor_type IN ('AGENT', 'ADMIN', 'SYSTEM')", name='ck_audit_actor_type'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('idempotency_records',
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('presentation_session_id', sa.UUID(), nullable=False),
    sa.Column('request_checksum', sa.String(length=64), nullable=False),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.create_table('knowledge_base',
    sa.Column('kb_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('model_class', sa.String(length=64), nullable=False),
    sa.Column('component_group', sa.String(length=128), nullable=False),
    sa.Column('material_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_metals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recovery_category', sa.String(length=128), nullable=False),
    sa.Column('statutory_framework_ref', sa.String(length=255), nullable=True),
    sa.Column('official_category_mapping', sa.String(length=128), nullable=True),
    sa.Column('provenance_source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['knowledge_base_versions.version_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('kb_id'),
    sa.UniqueConstraint('kb_id', 'version_id', name='uq_kb_id_version'),
    sa.UniqueConstraint('version_id', 'model_class', name='uq_version_class')
    )
    op.create_table('smart_bins',
    sa.Column('bin_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('bin_uid', sa.String(length=64), nullable=False),
    sa.Column('household_ref', sa.String(length=64), nullable=True),
    sa.Column('zone_name', sa.String(length=128), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('operational_status', postgresql.ENUM('NORMAL', 'NEAR_CAPACITY', 'COLLECTION_REQUIRED', 'MAINTENANCE_REQUIRED', 'DECOMMISSIONED', name='bin_operational_status_enum'), nullable=False),
    sa.Column('dry_fill_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('wet_fill_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ewaste_fill_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('battery_fill_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('battery_fill_pct BETWEEN 0 AND 100', name='ck_battery_fill'),
    sa.CheckConstraint('dry_fill_pct BETWEEN 0 AND 100', name='ck_dry_fill'),
    sa.CheckConstraint('ewaste_fill_pct BETWEEN 0 AND 100', name='ck_ewaste_fill'),
    sa.CheckConstraint('wet_fill_pct BETWEEN 0 AND 100', name='ck_wet_fill'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('bin_id'),
    sa.UniqueConstraint('bin_id', 'organization_id', name='uq_smart_bins_org_bin'),
    sa.UniqueConstraint('bin_uid')
    )
    op.create_table('auth_refresh_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.admin_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('jti')
    )
    op.create_table('bin_calibration_logs',
    sa.Column('calibration_id', sa.UUID(), nullable=False),
    sa.Column('bin_id', sa.UUID(), nullable=False),
    sa.Column('compartment', sa.SmallInteger(), nullable=False),
    sa.Column('empty_distance_cm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('full_distance_cm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('calibration_status', sa.String(length=32), nullable=False),
    sa.Column('calibrated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calibration_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("calibration_status IN ('REQUIRED', 'CALIBRATED', 'EXPIRED')", name='ck_calibration_status'),
    sa.CheckConstraint('compartment BETWEEN 1 AND 4', name='ck_calibration_compartment'),
    sa.ForeignKeyConstraint(['bin_id'], ['smart_bins.bin_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('calibration_id'),
    sa.UniqueConstraint('bin_id', 'compartment', name='uq_bin_compartment')
    )
    op.create_table('sensor_readings',
    sa.Column('reading_id', sa.UUID(), nullable=False),
    sa.Column('bin_id', sa.UUID(), nullable=False),
    sa.Column('compartment', postgresql.ENUM('DRY', 'WET', 'E_WASTE', 'BATTERY', name='waste_stream_enum'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fill_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temperature_celsius', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gas_index', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('raw_sensor_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fill_percentage BETWEEN 0 AND 100', name='ck_sensor_fill'),
    sa.CheckConstraint('humidity_percentage BETWEEN 0 AND 100', name='ck_sensor_humidity'),
    sa.ForeignKeyConstraint(['bin_id'], ['smart_bins.bin_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reading_id')
    )
    op.create_table('sensor_threshold_config',
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('bin_id', sa.UUID(), nullable=True),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('severity', postgresql.ENUM('INFO', 'WARNING', 'CRITICAL', name='alert_severity_enum'), nullable=False),
    sa.Column('operator', sa.String(length=16), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=False),
    sa.Column('calibration_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("metric IN ('DHT11_TEMPERATURE', 'MQ135_GAS_INDEX', 'ULTRASONIC_FILL')", name='ck_sensor_metric'),
    sa.CheckConstraint("operator IN ('>', '>=', '<', '<=', '=', 'CONFIGURABLE')", name='ck_sensor_operator'),
    sa.ForeignKeyConstraint(['bin_id'], ['smart_bins.bin_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('bin_id', 'metric', 'severity', name='uq_bin_metric_severity')
    )
    op.create_table('waste_detections',
    sa.Column('detection_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('bin_id', sa.UUID(), nullable=False),
    sa.Column('presentation_session_id', sa.UUID(), nullable=False),
    sa.Column('frame_reference_id', sa.String(length=128), nullable=False),
    sa.Column('model_class', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('waste_stream', postgresql.ENUM('DRY', 'WET', 'E_WASTE', 'BATTERY', name='waste_stream_enum'), nullable=False),
    sa.Column('target_compartment', sa.SmallInteger(), nullable=False),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('image_storage_path', sa.String(length=512), nullable=False),
    sa.Column('image_mime_type', sa.String(length=64), nullable=False),
    sa.Column('image_size_bytes', sa.Integer(), nullable=False),
    sa.Column('image_checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('status', postgresql.ENUM('DETECTED', 'CLASSIFIED', 'ENRICHED', 'PERSISTED_BASIC', 'AGENCY_FILTERED', 'ROUTE_PRIORITIZED', 'RECOMMENDATION_STORED', 'ALERT_DISPATCHED', 'COMPLETED', 'LOW_CONFIDENCE_REVIEW', 'UNSUPPORTED_CLASS', 'KNOWLEDGE_UNAVAILABLE', 'NO_SUITABLE_AGENCY', 'AGENT_FAILED', name='event_status_enum'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0.0000 AND 1.0000', name='ck_detection_confidence'),
    sa.CheckConstraint('target_compartment BETWEEN 1 AND 4', name='ck_target_compartment'),
    sa.ForeignKeyConstraint(['bin_id', 'organization_id'], ['smart_bins.bin_id', 'smart_bins.organization_id'], name='fk_waste_detections_bin_org', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('detection_id'),
    sa.UniqueConstraint('detection_id', 'organization_id', name='uq_detections_bin_org')
    )
    op.create_table('agency_recommendations',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('detection_id', sa.UUID(), nullable=False),
    sa.Column('selected_agency_id', sa.UUID(), nullable=True),
    sa.Column('candidate_agencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calculated_distance_km', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('route_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('decision_summary', sa.Text(), nullable=False),
    sa.Column('decision_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('route_score BETWEEN 0.0000 AND 1.0000', name='ck_route_score'),
    sa.ForeignKeyConstraint(['detection_id'], ['waste_detections.detection_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['selected_agency_id'], ['agencies.agency_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('recommendation_id'),
    sa.UniqueConstraint('detection_id')
    )
    op.create_table('agent_tool_executions',
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('agent_execution_id', sa.UUID(), nullable=False),
    sa.Column('detection_id', sa.UUID(), nullable=True),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', postgresql.ENUM('SUCCESS', 'FAILED', 'RETRY', 'TIMED_OUT', name='tool_execution_status_enum'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("tool_name IN ('classify_waste_type', 'check_environmental_risk', 'get_agency_options', 'calculate_route_priority', 'send_notification')", name='ck_agent_tool_name'),
    sa.ForeignKeyConstraint(['detection_id'], ['waste_detections.detection_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_table('alerts',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('alert_uid', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('bin_id', sa.UUID(), nullable=False),
    sa.Column('detection_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('severity', postgresql.ENUM('INFO', 'WARNING', 'CRITICAL', name='alert_severity_enum'), nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='alert_status_enum'), nullable=False),
    sa.Column('trigger_condition', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recipient_group', sa.String(length=128), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('email_delivery_status', postgresql.ENUM('PENDING', 'SENT', 'FAILED', name='notification_delivery_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['admins.admin_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bin_id', 'organization_id'], ['smart_bins.bin_id', 'smart_bins.organization_id'], name='fk_alerts_bin_org', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['detection_id'], ['waste_detections.detection_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by'], ['admins.admin_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('alert_id'),
    sa.UniqueConstraint('alert_uid')
    )
    op.create_table('ewaste_predictions',
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('detection_id', sa.UUID(), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('component_group', sa.String(length=128), nullable=False),
    sa.Column('material_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_metals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_recovery_category', sa.String(length=128), nullable=False),
    sa.Column('provenance_source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['waste_detections.detection_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['kb_id', 'version_id'], ['knowledge_base.kb_id', 'knowledge_base.version_id'], name='fk_ewaste_predictions_kb_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_id'], ['knowledge_base_versions.version_id'], name='fk_ewaste_predictions_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('prediction_id'),
    sa.UniqueConstraint('detection_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ewaste_predictions')
    op.drop_table('alerts')
    op.drop_table('agent_tool_executions')
    op.drop_table('agency_recommendations')
    op.drop_table('waste_detections')
    op.drop_table('sensor_threshold_config')
    op.drop_table('sensor_readings')
    op.drop_table('bin_calibration_logs')
    op.drop_table('auth_refresh_sessions')
    op.drop_table('smart_bins')
    op.drop_table('knowledge_base')
    op.drop_table('idempotency_records')
    op.drop_table('audit_events')
    op.drop_table('admins')
    op.drop_table('organizations')
    op.drop_table('knowledge_base_versions')
    op.drop_table('agencies')
    # ### end Alembic commands ###
